package com.aistar.pojo;

import java.util.ArrayList;
import java.util.List;

public class CouponHaveExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public CouponHaveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHaveIdIsNull() {
            addCriterion("have_id is null");
            return (Criteria) this;
        }

        public Criteria andHaveIdIsNotNull() {
            addCriterion("have_id is not null");
            return (Criteria) this;
        }

        public Criteria andHaveIdEqualTo(Integer value) {
            addCriterion("have_id =", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdNotEqualTo(Integer value) {
            addCriterion("have_id <>", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdGreaterThan(Integer value) {
            addCriterion("have_id >", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("have_id >=", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdLessThan(Integer value) {
            addCriterion("have_id <", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdLessThanOrEqualTo(Integer value) {
            addCriterion("have_id <=", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdIn(List<Integer> values) {
            addCriterion("have_id in", values, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdNotIn(List<Integer> values) {
            addCriterion("have_id not in", values, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdBetween(Integer value1, Integer value2) {
            addCriterion("have_id between", value1, value2, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdNotBetween(Integer value1, Integer value2) {
            addCriterion("have_id not between", value1, value2, "haveId");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(Integer value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(Integer value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(Integer value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(Integer value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(Integer value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<Integer> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<Integer> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(Integer value1, Integer value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouponIdEqualTo(Integer value) {
            addCriterion("coupon_id =", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotEqualTo(Integer value) {
            addCriterion("coupon_id <>", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThan(Integer value) {
            addCriterion("coupon_id >", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupon_id >=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThan(Integer value) {
            addCriterion("coupon_id <", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThanOrEqualTo(Integer value) {
            addCriterion("coupon_id <=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdIn(List<Integer> values) {
            addCriterion("coupon_id in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotIn(List<Integer> values) {
            addCriterion("coupon_id not in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdBetween(Integer value1, Integer value2) {
            addCriterion("coupon_id between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotBetween(Integer value1, Integer value2) {
            addCriterion("coupon_id not between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andHaveStatusIsNull() {
            addCriterion("have_status is null");
            return (Criteria) this;
        }

        public Criteria andHaveStatusIsNotNull() {
            addCriterion("have_status is not null");
            return (Criteria) this;
        }

        public Criteria andHaveStatusEqualTo(String value) {
            addCriterion("have_status =", value, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusNotEqualTo(String value) {
            addCriterion("have_status <>", value, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusGreaterThan(String value) {
            addCriterion("have_status >", value, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusGreaterThanOrEqualTo(String value) {
            addCriterion("have_status >=", value, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusLessThan(String value) {
            addCriterion("have_status <", value, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusLessThanOrEqualTo(String value) {
            addCriterion("have_status <=", value, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusLike(String value) {
            addCriterion("have_status like", value, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusNotLike(String value) {
            addCriterion("have_status not like", value, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusIn(List<String> values) {
            addCriterion("have_status in", values, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusNotIn(List<String> values) {
            addCriterion("have_status not in", values, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusBetween(String value1, String value2) {
            addCriterion("have_status between", value1, value2, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveStatusNotBetween(String value1, String value2) {
            addCriterion("have_status not between", value1, value2, "haveStatus");
            return (Criteria) this;
        }

        public Criteria andHaveOther1IsNull() {
            addCriterion("have_other1 is null");
            return (Criteria) this;
        }

        public Criteria andHaveOther1IsNotNull() {
            addCriterion("have_other1 is not null");
            return (Criteria) this;
        }

        public Criteria andHaveOther1EqualTo(String value) {
            addCriterion("have_other1 =", value, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1NotEqualTo(String value) {
            addCriterion("have_other1 <>", value, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1GreaterThan(String value) {
            addCriterion("have_other1 >", value, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1GreaterThanOrEqualTo(String value) {
            addCriterion("have_other1 >=", value, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1LessThan(String value) {
            addCriterion("have_other1 <", value, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1LessThanOrEqualTo(String value) {
            addCriterion("have_other1 <=", value, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1Like(String value) {
            addCriterion("have_other1 like", value, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1NotLike(String value) {
            addCriterion("have_other1 not like", value, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1In(List<String> values) {
            addCriterion("have_other1 in", values, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1NotIn(List<String> values) {
            addCriterion("have_other1 not in", values, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1Between(String value1, String value2) {
            addCriterion("have_other1 between", value1, value2, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther1NotBetween(String value1, String value2) {
            addCriterion("have_other1 not between", value1, value2, "haveOther1");
            return (Criteria) this;
        }

        public Criteria andHaveOther2IsNull() {
            addCriterion("have_other2 is null");
            return (Criteria) this;
        }

        public Criteria andHaveOther2IsNotNull() {
            addCriterion("have_other2 is not null");
            return (Criteria) this;
        }

        public Criteria andHaveOther2EqualTo(String value) {
            addCriterion("have_other2 =", value, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2NotEqualTo(String value) {
            addCriterion("have_other2 <>", value, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2GreaterThan(String value) {
            addCriterion("have_other2 >", value, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2GreaterThanOrEqualTo(String value) {
            addCriterion("have_other2 >=", value, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2LessThan(String value) {
            addCriterion("have_other2 <", value, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2LessThanOrEqualTo(String value) {
            addCriterion("have_other2 <=", value, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2Like(String value) {
            addCriterion("have_other2 like", value, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2NotLike(String value) {
            addCriterion("have_other2 not like", value, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2In(List<String> values) {
            addCriterion("have_other2 in", values, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2NotIn(List<String> values) {
            addCriterion("have_other2 not in", values, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2Between(String value1, String value2) {
            addCriterion("have_other2 between", value1, value2, "haveOther2");
            return (Criteria) this;
        }

        public Criteria andHaveOther2NotBetween(String value1, String value2) {
            addCriterion("have_other2 not between", value1, value2, "haveOther2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon_have
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 23 21:11:30 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}