package com.aistar.pojo;

import java.io.Serializable;

public class CouponHave implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_have.have_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer haveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_have.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_have.coupon_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_have.have_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String haveStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_have.have_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String haveOther1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_have.have_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String haveOther2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_have.have_id
     *
     * @return the value of coupon_have.have_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getHaveId() {
        return haveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_have.have_id
     *
     * @param haveId the value for coupon_have.have_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setHaveId(Integer haveId) {
        this.haveId = haveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_have.cust_id
     *
     * @return the value of coupon_have.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_have.cust_id
     *
     * @param custId the value for coupon_have.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_have.coupon_id
     *
     * @return the value of coupon_have.coupon_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_have.coupon_id
     *
     * @param couponId the value for coupon_have.coupon_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_have.have_status
     *
     * @return the value of coupon_have.have_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getHaveStatus() {
        return haveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_have.have_status
     *
     * @param haveStatus the value for coupon_have.have_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setHaveStatus(String haveStatus) {
        this.haveStatus = haveStatus == null ? null : haveStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_have.have_other1
     *
     * @return the value of coupon_have.have_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getHaveOther1() {
        return haveOther1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_have.have_other1
     *
     * @param haveOther1 the value for coupon_have.have_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setHaveOther1(String haveOther1) {
        this.haveOther1 = haveOther1 == null ? null : haveOther1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_have.have_other2
     *
     * @return the value of coupon_have.have_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getHaveOther2() {
        return haveOther2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_have.have_other2
     *
     * @param haveOther2 the value for coupon_have.have_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setHaveOther2(String haveOther2) {
        this.haveOther2 = haveOther2 == null ? null : haveOther2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", haveId=").append(haveId);
        sb.append(", custId=").append(custId);
        sb.append(", couponId=").append(couponId);
        sb.append(", haveStatus=").append(haveStatus);
        sb.append(", haveOther1=").append(haveOther1);
        sb.append(", haveOther2=").append(haveOther2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}