package com.aistar.pojo;

import java.io.Serializable;
import java.util.Date;

public class Coupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String couponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_startday
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Date couponStartday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_endday
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Date couponEndday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_money
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer couponMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_point
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer couponPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.full_money
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer fullMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_remark
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String couponRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String couponStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String couponOther1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String couponOther2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_id
     *
     * @return the value of coupon.coupon_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_id
     *
     * @param couponId the value for coupon.coupon_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_name
     *
     * @return the value of coupon.coupon_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_name
     *
     * @param couponName the value for coupon.coupon_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_startday
     *
     * @return the value of coupon.coupon_startday
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Date getCouponStartday() {
        return couponStartday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_startday
     *
     * @param couponStartday the value for coupon.coupon_startday
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponStartday(Date couponStartday) {
        this.couponStartday = couponStartday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_endday
     *
     * @return the value of coupon.coupon_endday
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Date getCouponEndday() {
        return couponEndday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_endday
     *
     * @param couponEndday the value for coupon.coupon_endday
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponEndday(Date couponEndday) {
        this.couponEndday = couponEndday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_money
     *
     * @return the value of coupon.coupon_money
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCouponMoney() {
        return couponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_money
     *
     * @param couponMoney the value for coupon.coupon_money
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponMoney(Integer couponMoney) {
        this.couponMoney = couponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_point
     *
     * @return the value of coupon.coupon_point
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCouponPoint() {
        return couponPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_point
     *
     * @param couponPoint the value for coupon.coupon_point
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponPoint(Integer couponPoint) {
        this.couponPoint = couponPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.full_money
     *
     * @return the value of coupon.full_money
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getFullMoney() {
        return fullMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.full_money
     *
     * @param fullMoney the value for coupon.full_money
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setFullMoney(Integer fullMoney) {
        this.fullMoney = fullMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_remark
     *
     * @return the value of coupon.coupon_remark
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCouponRemark() {
        return couponRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_remark
     *
     * @param couponRemark the value for coupon.coupon_remark
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponRemark(String couponRemark) {
        this.couponRemark = couponRemark == null ? null : couponRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_status
     *
     * @return the value of coupon.coupon_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_status
     *
     * @param couponStatus the value for coupon.coupon_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponStatus(String couponStatus) {
        this.couponStatus = couponStatus == null ? null : couponStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_other1
     *
     * @return the value of coupon.coupon_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCouponOther1() {
        return couponOther1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_other1
     *
     * @param couponOther1 the value for coupon.coupon_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponOther1(String couponOther1) {
        this.couponOther1 = couponOther1 == null ? null : couponOther1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_other2
     *
     * @return the value of coupon.coupon_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCouponOther2() {
        return couponOther2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_other2
     *
     * @param couponOther2 the value for coupon.coupon_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCouponOther2(String couponOther2) {
        this.couponOther2 = couponOther2 == null ? null : couponOther2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", couponId=").append(couponId);
        sb.append(", couponName=").append(couponName);
        sb.append(", couponStartday=").append(couponStartday);
        sb.append(", couponEndday=").append(couponEndday);
        sb.append(", couponMoney=").append(couponMoney);
        sb.append(", couponPoint=").append(couponPoint);
        sb.append(", fullMoney=").append(fullMoney);
        sb.append(", couponRemark=").append(couponRemark);
        sb.append(", couponStatus=").append(couponStatus);
        sb.append(", couponOther1=").append(couponOther1);
        sb.append(", couponOther2=").append(couponOther2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}