package com.aistar.pojo;

import java.io.Serializable;

public class Customer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_phonenum
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String custPhonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_password
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String custPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_ispainter
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer custIspainter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_default_add
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer custDefaultAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_nickname
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String custNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_gender
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String custGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_like
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String custLike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_point
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer custPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String custOther1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String custOther2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_id
     *
     * @return the value of customer.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_id
     *
     * @param custId the value for customer.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_phonenum
     *
     * @return the value of customer.cust_phonenum
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCustPhonenum() {
        return custPhonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_phonenum
     *
     * @param custPhonenum the value for customer.cust_phonenum
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustPhonenum(String custPhonenum) {
        this.custPhonenum = custPhonenum == null ? null : custPhonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_password
     *
     * @return the value of customer.cust_password
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCustPassword() {
        return custPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_password
     *
     * @param custPassword the value for customer.cust_password
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustPassword(String custPassword) {
        this.custPassword = custPassword == null ? null : custPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_ispainter
     *
     * @return the value of customer.cust_ispainter
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCustIspainter() {
        return custIspainter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_ispainter
     *
     * @param custIspainter the value for customer.cust_ispainter
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustIspainter(Integer custIspainter) {
        this.custIspainter = custIspainter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_default_add
     *
     * @return the value of customer.cust_default_add
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCustDefaultAdd() {
        return custDefaultAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_default_add
     *
     * @param custDefaultAdd the value for customer.cust_default_add
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustDefaultAdd(Integer custDefaultAdd) {
        this.custDefaultAdd = custDefaultAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_name
     *
     * @return the value of customer.cust_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_name
     *
     * @param custName the value for customer.cust_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_nickname
     *
     * @return the value of customer.cust_nickname
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCustNickname() {
        return custNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_nickname
     *
     * @param custNickname the value for customer.cust_nickname
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustNickname(String custNickname) {
        this.custNickname = custNickname == null ? null : custNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_gender
     *
     * @return the value of customer.cust_gender
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCustGender() {
        return custGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_gender
     *
     * @param custGender the value for customer.cust_gender
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustGender(String custGender) {
        this.custGender = custGender == null ? null : custGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_like
     *
     * @return the value of customer.cust_like
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCustLike() {
        return custLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_like
     *
     * @param custLike the value for customer.cust_like
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustLike(String custLike) {
        this.custLike = custLike == null ? null : custLike.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_point
     *
     * @return the value of customer.cust_point
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCustPoint() {
        return custPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_point
     *
     * @param custPoint the value for customer.cust_point
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustPoint(Integer custPoint) {
        this.custPoint = custPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_other1
     *
     * @return the value of customer.cust_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCustOther1() {
        return custOther1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_other1
     *
     * @param custOther1 the value for customer.cust_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustOther1(String custOther1) {
        this.custOther1 = custOther1 == null ? null : custOther1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_other2
     *
     * @return the value of customer.cust_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getCustOther2() {
        return custOther2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_other2
     *
     * @param custOther2 the value for customer.cust_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustOther2(String custOther2) {
        this.custOther2 = custOther2 == null ? null : custOther2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custId=").append(custId);
        sb.append(", custPhonenum=").append(custPhonenum);
        sb.append(", custPassword=").append(custPassword);
        sb.append(", custIspainter=").append(custIspainter);
        sb.append(", custDefaultAdd=").append(custDefaultAdd);
        sb.append(", custName=").append(custName);
        sb.append(", custNickname=").append(custNickname);
        sb.append(", custGender=").append(custGender);
        sb.append(", custLike=").append(custLike);
        sb.append(", custPoint=").append(custPoint);
        sb.append(", custOther1=").append(custOther1);
        sb.append(", custOther2=").append(custOther2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}