package com.aistar.pojo;

import java.util.ArrayList;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(Integer value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(Integer value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(Integer value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(Integer value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(Integer value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<Integer> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<Integer> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(Integer value1, Integer value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumIsNull() {
            addCriterion("cust_phonenum is null");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumIsNotNull() {
            addCriterion("cust_phonenum is not null");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumEqualTo(String value) {
            addCriterion("cust_phonenum =", value, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumNotEqualTo(String value) {
            addCriterion("cust_phonenum <>", value, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumGreaterThan(String value) {
            addCriterion("cust_phonenum >", value, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumGreaterThanOrEqualTo(String value) {
            addCriterion("cust_phonenum >=", value, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumLessThan(String value) {
            addCriterion("cust_phonenum <", value, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumLessThanOrEqualTo(String value) {
            addCriterion("cust_phonenum <=", value, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumLike(String value) {
            addCriterion("cust_phonenum like", value, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumNotLike(String value) {
            addCriterion("cust_phonenum not like", value, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumIn(List<String> values) {
            addCriterion("cust_phonenum in", values, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumNotIn(List<String> values) {
            addCriterion("cust_phonenum not in", values, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumBetween(String value1, String value2) {
            addCriterion("cust_phonenum between", value1, value2, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPhonenumNotBetween(String value1, String value2) {
            addCriterion("cust_phonenum not between", value1, value2, "custPhonenum");
            return (Criteria) this;
        }

        public Criteria andCustPasswordIsNull() {
            addCriterion("cust_password is null");
            return (Criteria) this;
        }

        public Criteria andCustPasswordIsNotNull() {
            addCriterion("cust_password is not null");
            return (Criteria) this;
        }

        public Criteria andCustPasswordEqualTo(String value) {
            addCriterion("cust_password =", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordNotEqualTo(String value) {
            addCriterion("cust_password <>", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordGreaterThan(String value) {
            addCriterion("cust_password >", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("cust_password >=", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordLessThan(String value) {
            addCriterion("cust_password <", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordLessThanOrEqualTo(String value) {
            addCriterion("cust_password <=", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordLike(String value) {
            addCriterion("cust_password like", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordNotLike(String value) {
            addCriterion("cust_password not like", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordIn(List<String> values) {
            addCriterion("cust_password in", values, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordNotIn(List<String> values) {
            addCriterion("cust_password not in", values, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordBetween(String value1, String value2) {
            addCriterion("cust_password between", value1, value2, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordNotBetween(String value1, String value2) {
            addCriterion("cust_password not between", value1, value2, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustIspainterIsNull() {
            addCriterion("cust_ispainter is null");
            return (Criteria) this;
        }

        public Criteria andCustIspainterIsNotNull() {
            addCriterion("cust_ispainter is not null");
            return (Criteria) this;
        }

        public Criteria andCustIspainterEqualTo(Integer value) {
            addCriterion("cust_ispainter =", value, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterNotEqualTo(Integer value) {
            addCriterion("cust_ispainter <>", value, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterGreaterThan(Integer value) {
            addCriterion("cust_ispainter >", value, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_ispainter >=", value, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterLessThan(Integer value) {
            addCriterion("cust_ispainter <", value, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterLessThanOrEqualTo(Integer value) {
            addCriterion("cust_ispainter <=", value, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterIn(List<Integer> values) {
            addCriterion("cust_ispainter in", values, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterNotIn(List<Integer> values) {
            addCriterion("cust_ispainter not in", values, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterBetween(Integer value1, Integer value2) {
            addCriterion("cust_ispainter between", value1, value2, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustIspainterNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_ispainter not between", value1, value2, "custIspainter");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddIsNull() {
            addCriterion("cust_default_add is null");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddIsNotNull() {
            addCriterion("cust_default_add is not null");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddEqualTo(Integer value) {
            addCriterion("cust_default_add =", value, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddNotEqualTo(Integer value) {
            addCriterion("cust_default_add <>", value, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddGreaterThan(Integer value) {
            addCriterion("cust_default_add >", value, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_default_add >=", value, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddLessThan(Integer value) {
            addCriterion("cust_default_add <", value, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddLessThanOrEqualTo(Integer value) {
            addCriterion("cust_default_add <=", value, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddIn(List<Integer> values) {
            addCriterion("cust_default_add in", values, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddNotIn(List<Integer> values) {
            addCriterion("cust_default_add not in", values, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddBetween(Integer value1, Integer value2) {
            addCriterion("cust_default_add between", value1, value2, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustDefaultAddNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_default_add not between", value1, value2, "custDefaultAdd");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("cust_name is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("cust_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("cust_name =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("cust_name <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("cust_name >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_name >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("cust_name <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("cust_name <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("cust_name like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("cust_name not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("cust_name in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("cust_name not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("cust_name between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("cust_name not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNicknameIsNull() {
            addCriterion("cust_nickname is null");
            return (Criteria) this;
        }

        public Criteria andCustNicknameIsNotNull() {
            addCriterion("cust_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andCustNicknameEqualTo(String value) {
            addCriterion("cust_nickname =", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameNotEqualTo(String value) {
            addCriterion("cust_nickname <>", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameGreaterThan(String value) {
            addCriterion("cust_nickname >", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_nickname >=", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameLessThan(String value) {
            addCriterion("cust_nickname <", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameLessThanOrEqualTo(String value) {
            addCriterion("cust_nickname <=", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameLike(String value) {
            addCriterion("cust_nickname like", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameNotLike(String value) {
            addCriterion("cust_nickname not like", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameIn(List<String> values) {
            addCriterion("cust_nickname in", values, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameNotIn(List<String> values) {
            addCriterion("cust_nickname not in", values, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameBetween(String value1, String value2) {
            addCriterion("cust_nickname between", value1, value2, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameNotBetween(String value1, String value2) {
            addCriterion("cust_nickname not between", value1, value2, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustGenderIsNull() {
            addCriterion("cust_gender is null");
            return (Criteria) this;
        }

        public Criteria andCustGenderIsNotNull() {
            addCriterion("cust_gender is not null");
            return (Criteria) this;
        }

        public Criteria andCustGenderEqualTo(String value) {
            addCriterion("cust_gender =", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderNotEqualTo(String value) {
            addCriterion("cust_gender <>", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderGreaterThan(String value) {
            addCriterion("cust_gender >", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderGreaterThanOrEqualTo(String value) {
            addCriterion("cust_gender >=", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderLessThan(String value) {
            addCriterion("cust_gender <", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderLessThanOrEqualTo(String value) {
            addCriterion("cust_gender <=", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderLike(String value) {
            addCriterion("cust_gender like", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderNotLike(String value) {
            addCriterion("cust_gender not like", value, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderIn(List<String> values) {
            addCriterion("cust_gender in", values, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderNotIn(List<String> values) {
            addCriterion("cust_gender not in", values, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderBetween(String value1, String value2) {
            addCriterion("cust_gender between", value1, value2, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustGenderNotBetween(String value1, String value2) {
            addCriterion("cust_gender not between", value1, value2, "custGender");
            return (Criteria) this;
        }

        public Criteria andCustLikeIsNull() {
            addCriterion("cust_like is null");
            return (Criteria) this;
        }

        public Criteria andCustLikeIsNotNull() {
            addCriterion("cust_like is not null");
            return (Criteria) this;
        }

        public Criteria andCustLikeEqualTo(String value) {
            addCriterion("cust_like =", value, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeNotEqualTo(String value) {
            addCriterion("cust_like <>", value, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeGreaterThan(String value) {
            addCriterion("cust_like >", value, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeGreaterThanOrEqualTo(String value) {
            addCriterion("cust_like >=", value, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeLessThan(String value) {
            addCriterion("cust_like <", value, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeLessThanOrEqualTo(String value) {
            addCriterion("cust_like <=", value, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeLike(String value) {
            addCriterion("cust_like like", value, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeNotLike(String value) {
            addCriterion("cust_like not like", value, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeIn(List<String> values) {
            addCriterion("cust_like in", values, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeNotIn(List<String> values) {
            addCriterion("cust_like not in", values, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeBetween(String value1, String value2) {
            addCriterion("cust_like between", value1, value2, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustLikeNotBetween(String value1, String value2) {
            addCriterion("cust_like not between", value1, value2, "custLike");
            return (Criteria) this;
        }

        public Criteria andCustPointIsNull() {
            addCriterion("cust_point is null");
            return (Criteria) this;
        }

        public Criteria andCustPointIsNotNull() {
            addCriterion("cust_point is not null");
            return (Criteria) this;
        }

        public Criteria andCustPointEqualTo(Integer value) {
            addCriterion("cust_point =", value, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointNotEqualTo(Integer value) {
            addCriterion("cust_point <>", value, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointGreaterThan(Integer value) {
            addCriterion("cust_point >", value, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_point >=", value, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointLessThan(Integer value) {
            addCriterion("cust_point <", value, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointLessThanOrEqualTo(Integer value) {
            addCriterion("cust_point <=", value, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointIn(List<Integer> values) {
            addCriterion("cust_point in", values, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointNotIn(List<Integer> values) {
            addCriterion("cust_point not in", values, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointBetween(Integer value1, Integer value2) {
            addCriterion("cust_point between", value1, value2, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustPointNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_point not between", value1, value2, "custPoint");
            return (Criteria) this;
        }

        public Criteria andCustOther1IsNull() {
            addCriterion("cust_other1 is null");
            return (Criteria) this;
        }

        public Criteria andCustOther1IsNotNull() {
            addCriterion("cust_other1 is not null");
            return (Criteria) this;
        }

        public Criteria andCustOther1EqualTo(String value) {
            addCriterion("cust_other1 =", value, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1NotEqualTo(String value) {
            addCriterion("cust_other1 <>", value, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1GreaterThan(String value) {
            addCriterion("cust_other1 >", value, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1GreaterThanOrEqualTo(String value) {
            addCriterion("cust_other1 >=", value, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1LessThan(String value) {
            addCriterion("cust_other1 <", value, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1LessThanOrEqualTo(String value) {
            addCriterion("cust_other1 <=", value, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1Like(String value) {
            addCriterion("cust_other1 like", value, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1NotLike(String value) {
            addCriterion("cust_other1 not like", value, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1In(List<String> values) {
            addCriterion("cust_other1 in", values, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1NotIn(List<String> values) {
            addCriterion("cust_other1 not in", values, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1Between(String value1, String value2) {
            addCriterion("cust_other1 between", value1, value2, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther1NotBetween(String value1, String value2) {
            addCriterion("cust_other1 not between", value1, value2, "custOther1");
            return (Criteria) this;
        }

        public Criteria andCustOther2IsNull() {
            addCriterion("cust_other2 is null");
            return (Criteria) this;
        }

        public Criteria andCustOther2IsNotNull() {
            addCriterion("cust_other2 is not null");
            return (Criteria) this;
        }

        public Criteria andCustOther2EqualTo(String value) {
            addCriterion("cust_other2 =", value, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2NotEqualTo(String value) {
            addCriterion("cust_other2 <>", value, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2GreaterThan(String value) {
            addCriterion("cust_other2 >", value, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2GreaterThanOrEqualTo(String value) {
            addCriterion("cust_other2 >=", value, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2LessThan(String value) {
            addCriterion("cust_other2 <", value, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2LessThanOrEqualTo(String value) {
            addCriterion("cust_other2 <=", value, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2Like(String value) {
            addCriterion("cust_other2 like", value, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2NotLike(String value) {
            addCriterion("cust_other2 not like", value, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2In(List<String> values) {
            addCriterion("cust_other2 in", values, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2NotIn(List<String> values) {
            addCriterion("cust_other2 not in", values, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2Between(String value1, String value2) {
            addCriterion("cust_other2 between", value1, value2, "custOther2");
            return (Criteria) this;
        }

        public Criteria andCustOther2NotBetween(String value1, String value2) {
            addCriterion("cust_other2 not between", value1, value2, "custOther2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 23 21:11:30 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}