package com.aistar.pojo;

import java.io.Serializable;
import java.util.Date;

public class Myorder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.order_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.order_date
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.add_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer addId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.order_method
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer orderMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.have_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer haveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.order_price
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Double orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.order_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.order_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String orderOther1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myorder.order_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String orderOther2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.order_id
     *
     * @return the value of myorder.order_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.order_id
     *
     * @param orderId the value for myorder.order_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.cust_id
     *
     * @return the value of myorder.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.cust_id
     *
     * @param custId the value for myorder.cust_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.order_date
     *
     * @return the value of myorder.order_date
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.order_date
     *
     * @param orderDate the value for myorder.order_date
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.add_id
     *
     * @return the value of myorder.add_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.add_id
     *
     * @param addId the value for myorder.add_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setAddId(Integer addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.order_method
     *
     * @return the value of myorder.order_method
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getOrderMethod() {
        return orderMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.order_method
     *
     * @param orderMethod the value for myorder.order_method
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderMethod(Integer orderMethod) {
        this.orderMethod = orderMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.have_id
     *
     * @return the value of myorder.have_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getHaveId() {
        return haveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.have_id
     *
     * @param haveId the value for myorder.have_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setHaveId(Integer haveId) {
        this.haveId = haveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.order_price
     *
     * @return the value of myorder.order_price
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Double getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.order_price
     *
     * @param orderPrice the value for myorder.order_price
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderPrice(Double orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.order_status
     *
     * @return the value of myorder.order_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.order_status
     *
     * @param orderStatus the value for myorder.order_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.order_other1
     *
     * @return the value of myorder.order_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getOrderOther1() {
        return orderOther1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.order_other1
     *
     * @param orderOther1 the value for myorder.order_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderOther1(String orderOther1) {
        this.orderOther1 = orderOther1 == null ? null : orderOther1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myorder.order_other2
     *
     * @return the value of myorder.order_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getOrderOther2() {
        return orderOther2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myorder.order_other2
     *
     * @param orderOther2 the value for myorder.order_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderOther2(String orderOther2) {
        this.orderOther2 = orderOther2 == null ? null : orderOther2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", custId=").append(custId);
        sb.append(", orderDate=").append(orderDate);
        sb.append(", addId=").append(addId);
        sb.append(", orderMethod=").append(orderMethod);
        sb.append(", haveId=").append(haveId);
        sb.append(", orderPrice=").append(orderPrice);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", orderOther1=").append(orderOther1);
        sb.append(", orderOther2=").append(orderOther2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}