package com.aistar.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MyorderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public MyorderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(Integer value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(Integer value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(Integer value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(Integer value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(Integer value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<Integer> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<Integer> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(Integer value1, Integer value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNull() {
            addCriterion("order_date is null");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNotNull() {
            addCriterion("order_date is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDateEqualTo(Date value) {
            addCriterion("order_date =", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotEqualTo(Date value) {
            addCriterion("order_date <>", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThan(Date value) {
            addCriterion("order_date >", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThanOrEqualTo(Date value) {
            addCriterion("order_date >=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThan(Date value) {
            addCriterion("order_date <", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThanOrEqualTo(Date value) {
            addCriterion("order_date <=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateIn(List<Date> values) {
            addCriterion("order_date in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotIn(List<Date> values) {
            addCriterion("order_date not in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateBetween(Date value1, Date value2) {
            addCriterion("order_date between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotBetween(Date value1, Date value2) {
            addCriterion("order_date not between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andAddIdIsNull() {
            addCriterion("add_id is null");
            return (Criteria) this;
        }

        public Criteria andAddIdIsNotNull() {
            addCriterion("add_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddIdEqualTo(Integer value) {
            addCriterion("add_id =", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdNotEqualTo(Integer value) {
            addCriterion("add_id <>", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdGreaterThan(Integer value) {
            addCriterion("add_id >", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("add_id >=", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdLessThan(Integer value) {
            addCriterion("add_id <", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdLessThanOrEqualTo(Integer value) {
            addCriterion("add_id <=", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdIn(List<Integer> values) {
            addCriterion("add_id in", values, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdNotIn(List<Integer> values) {
            addCriterion("add_id not in", values, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdBetween(Integer value1, Integer value2) {
            addCriterion("add_id between", value1, value2, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdNotBetween(Integer value1, Integer value2) {
            addCriterion("add_id not between", value1, value2, "addId");
            return (Criteria) this;
        }

        public Criteria andOrderMethodIsNull() {
            addCriterion("order_method is null");
            return (Criteria) this;
        }

        public Criteria andOrderMethodIsNotNull() {
            addCriterion("order_method is not null");
            return (Criteria) this;
        }

        public Criteria andOrderMethodEqualTo(Integer value) {
            addCriterion("order_method =", value, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodNotEqualTo(Integer value) {
            addCriterion("order_method <>", value, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodGreaterThan(Integer value) {
            addCriterion("order_method >", value, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_method >=", value, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodLessThan(Integer value) {
            addCriterion("order_method <", value, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodLessThanOrEqualTo(Integer value) {
            addCriterion("order_method <=", value, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodIn(List<Integer> values) {
            addCriterion("order_method in", values, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodNotIn(List<Integer> values) {
            addCriterion("order_method not in", values, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodBetween(Integer value1, Integer value2) {
            addCriterion("order_method between", value1, value2, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andOrderMethodNotBetween(Integer value1, Integer value2) {
            addCriterion("order_method not between", value1, value2, "orderMethod");
            return (Criteria) this;
        }

        public Criteria andHaveIdIsNull() {
            addCriterion("have_id is null");
            return (Criteria) this;
        }

        public Criteria andHaveIdIsNotNull() {
            addCriterion("have_id is not null");
            return (Criteria) this;
        }

        public Criteria andHaveIdEqualTo(Integer value) {
            addCriterion("have_id =", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdNotEqualTo(Integer value) {
            addCriterion("have_id <>", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdGreaterThan(Integer value) {
            addCriterion("have_id >", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("have_id >=", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdLessThan(Integer value) {
            addCriterion("have_id <", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdLessThanOrEqualTo(Integer value) {
            addCriterion("have_id <=", value, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdIn(List<Integer> values) {
            addCriterion("have_id in", values, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdNotIn(List<Integer> values) {
            addCriterion("have_id not in", values, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdBetween(Integer value1, Integer value2) {
            addCriterion("have_id between", value1, value2, "haveId");
            return (Criteria) this;
        }

        public Criteria andHaveIdNotBetween(Integer value1, Integer value2) {
            addCriterion("have_id not between", value1, value2, "haveId");
            return (Criteria) this;
        }

        public Criteria andOrderPriceIsNull() {
            addCriterion("order_price is null");
            return (Criteria) this;
        }

        public Criteria andOrderPriceIsNotNull() {
            addCriterion("order_price is not null");
            return (Criteria) this;
        }

        public Criteria andOrderPriceEqualTo(Double value) {
            addCriterion("order_price =", value, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceNotEqualTo(Double value) {
            addCriterion("order_price <>", value, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceGreaterThan(Double value) {
            addCriterion("order_price >", value, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("order_price >=", value, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceLessThan(Double value) {
            addCriterion("order_price <", value, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceLessThanOrEqualTo(Double value) {
            addCriterion("order_price <=", value, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceIn(List<Double> values) {
            addCriterion("order_price in", values, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceNotIn(List<Double> values) {
            addCriterion("order_price not in", values, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceBetween(Double value1, Double value2) {
            addCriterion("order_price between", value1, value2, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPriceNotBetween(Double value1, Double value2) {
            addCriterion("order_price not between", value1, value2, "orderPrice");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderOther1IsNull() {
            addCriterion("order_other1 is null");
            return (Criteria) this;
        }

        public Criteria andOrderOther1IsNotNull() {
            addCriterion("order_other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOrderOther1EqualTo(String value) {
            addCriterion("order_other1 =", value, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1NotEqualTo(String value) {
            addCriterion("order_other1 <>", value, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1GreaterThan(String value) {
            addCriterion("order_other1 >", value, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1GreaterThanOrEqualTo(String value) {
            addCriterion("order_other1 >=", value, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1LessThan(String value) {
            addCriterion("order_other1 <", value, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1LessThanOrEqualTo(String value) {
            addCriterion("order_other1 <=", value, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1Like(String value) {
            addCriterion("order_other1 like", value, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1NotLike(String value) {
            addCriterion("order_other1 not like", value, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1In(List<String> values) {
            addCriterion("order_other1 in", values, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1NotIn(List<String> values) {
            addCriterion("order_other1 not in", values, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1Between(String value1, String value2) {
            addCriterion("order_other1 between", value1, value2, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther1NotBetween(String value1, String value2) {
            addCriterion("order_other1 not between", value1, value2, "orderOther1");
            return (Criteria) this;
        }

        public Criteria andOrderOther2IsNull() {
            addCriterion("order_other2 is null");
            return (Criteria) this;
        }

        public Criteria andOrderOther2IsNotNull() {
            addCriterion("order_other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOrderOther2EqualTo(String value) {
            addCriterion("order_other2 =", value, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2NotEqualTo(String value) {
            addCriterion("order_other2 <>", value, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2GreaterThan(String value) {
            addCriterion("order_other2 >", value, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2GreaterThanOrEqualTo(String value) {
            addCriterion("order_other2 >=", value, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2LessThan(String value) {
            addCriterion("order_other2 <", value, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2LessThanOrEqualTo(String value) {
            addCriterion("order_other2 <=", value, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2Like(String value) {
            addCriterion("order_other2 like", value, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2NotLike(String value) {
            addCriterion("order_other2 not like", value, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2In(List<String> values) {
            addCriterion("order_other2 in", values, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2NotIn(List<String> values) {
            addCriterion("order_other2 not in", values, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2Between(String value1, String value2) {
            addCriterion("order_other2 between", value1, value2, "orderOther2");
            return (Criteria) this;
        }

        public Criteria andOrderOther2NotBetween(String value1, String value2) {
            addCriterion("order_other2 not between", value1, value2, "orderOther2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myorder
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 23 21:11:30 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}