package com.aistar.pojo;

import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProIdIsNull() {
            addCriterion("pro_id is null");
            return (Criteria) this;
        }

        public Criteria andProIdIsNotNull() {
            addCriterion("pro_id is not null");
            return (Criteria) this;
        }

        public Criteria andProIdEqualTo(Integer value) {
            addCriterion("pro_id =", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotEqualTo(Integer value) {
            addCriterion("pro_id <>", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdGreaterThan(Integer value) {
            addCriterion("pro_id >", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pro_id >=", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdLessThan(Integer value) {
            addCriterion("pro_id <", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdLessThanOrEqualTo(Integer value) {
            addCriterion("pro_id <=", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdIn(List<Integer> values) {
            addCriterion("pro_id in", values, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotIn(List<Integer> values) {
            addCriterion("pro_id not in", values, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdBetween(Integer value1, Integer value2) {
            addCriterion("pro_id between", value1, value2, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pro_id not between", value1, value2, "proId");
            return (Criteria) this;
        }

        public Criteria andProNameIsNull() {
            addCriterion("pro_name is null");
            return (Criteria) this;
        }

        public Criteria andProNameIsNotNull() {
            addCriterion("pro_name is not null");
            return (Criteria) this;
        }

        public Criteria andProNameEqualTo(String value) {
            addCriterion("pro_name =", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotEqualTo(String value) {
            addCriterion("pro_name <>", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameGreaterThan(String value) {
            addCriterion("pro_name >", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameGreaterThanOrEqualTo(String value) {
            addCriterion("pro_name >=", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLessThan(String value) {
            addCriterion("pro_name <", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLessThanOrEqualTo(String value) {
            addCriterion("pro_name <=", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLike(String value) {
            addCriterion("pro_name like", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotLike(String value) {
            addCriterion("pro_name not like", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameIn(List<String> values) {
            addCriterion("pro_name in", values, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotIn(List<String> values) {
            addCriterion("pro_name not in", values, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameBetween(String value1, String value2) {
            addCriterion("pro_name between", value1, value2, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotBetween(String value1, String value2) {
            addCriterion("pro_name not between", value1, value2, "proName");
            return (Criteria) this;
        }

        public Criteria andProPriceIsNull() {
            addCriterion("pro_price is null");
            return (Criteria) this;
        }

        public Criteria andProPriceIsNotNull() {
            addCriterion("pro_price is not null");
            return (Criteria) this;
        }

        public Criteria andProPriceEqualTo(Double value) {
            addCriterion("pro_price =", value, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceNotEqualTo(Double value) {
            addCriterion("pro_price <>", value, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceGreaterThan(Double value) {
            addCriterion("pro_price >", value, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("pro_price >=", value, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceLessThan(Double value) {
            addCriterion("pro_price <", value, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceLessThanOrEqualTo(Double value) {
            addCriterion("pro_price <=", value, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceIn(List<Double> values) {
            addCriterion("pro_price in", values, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceNotIn(List<Double> values) {
            addCriterion("pro_price not in", values, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceBetween(Double value1, Double value2) {
            addCriterion("pro_price between", value1, value2, "proPrice");
            return (Criteria) this;
        }

        public Criteria andProPriceNotBetween(Double value1, Double value2) {
            addCriterion("pro_price not between", value1, value2, "proPrice");
            return (Criteria) this;
        }

        public Criteria andWriterIdIsNull() {
            addCriterion("writer_id is null");
            return (Criteria) this;
        }

        public Criteria andWriterIdIsNotNull() {
            addCriterion("writer_id is not null");
            return (Criteria) this;
        }

        public Criteria andWriterIdEqualTo(Integer value) {
            addCriterion("writer_id =", value, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdNotEqualTo(Integer value) {
            addCriterion("writer_id <>", value, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdGreaterThan(Integer value) {
            addCriterion("writer_id >", value, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("writer_id >=", value, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdLessThan(Integer value) {
            addCriterion("writer_id <", value, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdLessThanOrEqualTo(Integer value) {
            addCriterion("writer_id <=", value, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdIn(List<Integer> values) {
            addCriterion("writer_id in", values, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdNotIn(List<Integer> values) {
            addCriterion("writer_id not in", values, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdBetween(Integer value1, Integer value2) {
            addCriterion("writer_id between", value1, value2, "writerId");
            return (Criteria) this;
        }

        public Criteria andWriterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("writer_id not between", value1, value2, "writerId");
            return (Criteria) this;
        }

        public Criteria andProStatusIsNull() {
            addCriterion("pro_status is null");
            return (Criteria) this;
        }

        public Criteria andProStatusIsNotNull() {
            addCriterion("pro_status is not null");
            return (Criteria) this;
        }

        public Criteria andProStatusEqualTo(Integer value) {
            addCriterion("pro_status =", value, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusNotEqualTo(Integer value) {
            addCriterion("pro_status <>", value, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusGreaterThan(Integer value) {
            addCriterion("pro_status >", value, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("pro_status >=", value, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusLessThan(Integer value) {
            addCriterion("pro_status <", value, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusLessThanOrEqualTo(Integer value) {
            addCriterion("pro_status <=", value, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusIn(List<Integer> values) {
            addCriterion("pro_status in", values, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusNotIn(List<Integer> values) {
            addCriterion("pro_status not in", values, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusBetween(Integer value1, Integer value2) {
            addCriterion("pro_status between", value1, value2, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("pro_status not between", value1, value2, "proStatus");
            return (Criteria) this;
        }

        public Criteria andProSizeIsNull() {
            addCriterion("pro_size is null");
            return (Criteria) this;
        }

        public Criteria andProSizeIsNotNull() {
            addCriterion("pro_size is not null");
            return (Criteria) this;
        }

        public Criteria andProSizeEqualTo(String value) {
            addCriterion("pro_size =", value, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeNotEqualTo(String value) {
            addCriterion("pro_size <>", value, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeGreaterThan(String value) {
            addCriterion("pro_size >", value, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeGreaterThanOrEqualTo(String value) {
            addCriterion("pro_size >=", value, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeLessThan(String value) {
            addCriterion("pro_size <", value, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeLessThanOrEqualTo(String value) {
            addCriterion("pro_size <=", value, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeLike(String value) {
            addCriterion("pro_size like", value, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeNotLike(String value) {
            addCriterion("pro_size not like", value, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeIn(List<String> values) {
            addCriterion("pro_size in", values, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeNotIn(List<String> values) {
            addCriterion("pro_size not in", values, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeBetween(String value1, String value2) {
            addCriterion("pro_size between", value1, value2, "proSize");
            return (Criteria) this;
        }

        public Criteria andProSizeNotBetween(String value1, String value2) {
            addCriterion("pro_size not between", value1, value2, "proSize");
            return (Criteria) this;
        }

        public Criteria andProDateIsNull() {
            addCriterion("pro_date is null");
            return (Criteria) this;
        }

        public Criteria andProDateIsNotNull() {
            addCriterion("pro_date is not null");
            return (Criteria) this;
        }

        public Criteria andProDateEqualTo(String value) {
            addCriterion("pro_date =", value, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateNotEqualTo(String value) {
            addCriterion("pro_date <>", value, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateGreaterThan(String value) {
            addCriterion("pro_date >", value, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateGreaterThanOrEqualTo(String value) {
            addCriterion("pro_date >=", value, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateLessThan(String value) {
            addCriterion("pro_date <", value, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateLessThanOrEqualTo(String value) {
            addCriterion("pro_date <=", value, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateLike(String value) {
            addCriterion("pro_date like", value, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateNotLike(String value) {
            addCriterion("pro_date not like", value, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateIn(List<String> values) {
            addCriterion("pro_date in", values, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateNotIn(List<String> values) {
            addCriterion("pro_date not in", values, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateBetween(String value1, String value2) {
            addCriterion("pro_date between", value1, value2, "proDate");
            return (Criteria) this;
        }

        public Criteria andProDateNotBetween(String value1, String value2) {
            addCriterion("pro_date not between", value1, value2, "proDate");
            return (Criteria) this;
        }

        public Criteria andKindIdIsNull() {
            addCriterion("kind_id is null");
            return (Criteria) this;
        }

        public Criteria andKindIdIsNotNull() {
            addCriterion("kind_id is not null");
            return (Criteria) this;
        }

        public Criteria andKindIdEqualTo(Integer value) {
            addCriterion("kind_id =", value, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdNotEqualTo(Integer value) {
            addCriterion("kind_id <>", value, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdGreaterThan(Integer value) {
            addCriterion("kind_id >", value, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("kind_id >=", value, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdLessThan(Integer value) {
            addCriterion("kind_id <", value, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdLessThanOrEqualTo(Integer value) {
            addCriterion("kind_id <=", value, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdIn(List<Integer> values) {
            addCriterion("kind_id in", values, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdNotIn(List<Integer> values) {
            addCriterion("kind_id not in", values, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdBetween(Integer value1, Integer value2) {
            addCriterion("kind_id between", value1, value2, "kindId");
            return (Criteria) this;
        }

        public Criteria andKindIdNotBetween(Integer value1, Integer value2) {
            addCriterion("kind_id not between", value1, value2, "kindId");
            return (Criteria) this;
        }

        public Criteria andThemeIdIsNull() {
            addCriterion("theme_id is null");
            return (Criteria) this;
        }

        public Criteria andThemeIdIsNotNull() {
            addCriterion("theme_id is not null");
            return (Criteria) this;
        }

        public Criteria andThemeIdEqualTo(Integer value) {
            addCriterion("theme_id =", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdNotEqualTo(Integer value) {
            addCriterion("theme_id <>", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdGreaterThan(Integer value) {
            addCriterion("theme_id >", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("theme_id >=", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdLessThan(Integer value) {
            addCriterion("theme_id <", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdLessThanOrEqualTo(Integer value) {
            addCriterion("theme_id <=", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdIn(List<Integer> values) {
            addCriterion("theme_id in", values, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdNotIn(List<Integer> values) {
            addCriterion("theme_id not in", values, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdBetween(Integer value1, Integer value2) {
            addCriterion("theme_id between", value1, value2, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("theme_id not between", value1, value2, "themeId");
            return (Criteria) this;
        }

        public Criteria andProMaterialIsNull() {
            addCriterion("pro_material is null");
            return (Criteria) this;
        }

        public Criteria andProMaterialIsNotNull() {
            addCriterion("pro_material is not null");
            return (Criteria) this;
        }

        public Criteria andProMaterialEqualTo(String value) {
            addCriterion("pro_material =", value, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialNotEqualTo(String value) {
            addCriterion("pro_material <>", value, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialGreaterThan(String value) {
            addCriterion("pro_material >", value, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("pro_material >=", value, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialLessThan(String value) {
            addCriterion("pro_material <", value, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialLessThanOrEqualTo(String value) {
            addCriterion("pro_material <=", value, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialLike(String value) {
            addCriterion("pro_material like", value, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialNotLike(String value) {
            addCriterion("pro_material not like", value, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialIn(List<String> values) {
            addCriterion("pro_material in", values, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialNotIn(List<String> values) {
            addCriterion("pro_material not in", values, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialBetween(String value1, String value2) {
            addCriterion("pro_material between", value1, value2, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProMaterialNotBetween(String value1, String value2) {
            addCriterion("pro_material not between", value1, value2, "proMaterial");
            return (Criteria) this;
        }

        public Criteria andProKindIsNull() {
            addCriterion("pro_kind is null");
            return (Criteria) this;
        }

        public Criteria andProKindIsNotNull() {
            addCriterion("pro_kind is not null");
            return (Criteria) this;
        }

        public Criteria andProKindEqualTo(Integer value) {
            addCriterion("pro_kind =", value, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindNotEqualTo(Integer value) {
            addCriterion("pro_kind <>", value, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindGreaterThan(Integer value) {
            addCriterion("pro_kind >", value, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindGreaterThanOrEqualTo(Integer value) {
            addCriterion("pro_kind >=", value, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindLessThan(Integer value) {
            addCriterion("pro_kind <", value, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindLessThanOrEqualTo(Integer value) {
            addCriterion("pro_kind <=", value, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindIn(List<Integer> values) {
            addCriterion("pro_kind in", values, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindNotIn(List<Integer> values) {
            addCriterion("pro_kind not in", values, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindBetween(Integer value1, Integer value2) {
            addCriterion("pro_kind between", value1, value2, "proKind");
            return (Criteria) this;
        }

        public Criteria andProKindNotBetween(Integer value1, Integer value2) {
            addCriterion("pro_kind not between", value1, value2, "proKind");
            return (Criteria) this;
        }

        public Criteria andProOther1IsNull() {
            addCriterion("pro_other1 is null");
            return (Criteria) this;
        }

        public Criteria andProOther1IsNotNull() {
            addCriterion("pro_other1 is not null");
            return (Criteria) this;
        }

        public Criteria andProOther1EqualTo(String value) {
            addCriterion("pro_other1 =", value, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1NotEqualTo(String value) {
            addCriterion("pro_other1 <>", value, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1GreaterThan(String value) {
            addCriterion("pro_other1 >", value, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1GreaterThanOrEqualTo(String value) {
            addCriterion("pro_other1 >=", value, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1LessThan(String value) {
            addCriterion("pro_other1 <", value, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1LessThanOrEqualTo(String value) {
            addCriterion("pro_other1 <=", value, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1Like(String value) {
            addCriterion("pro_other1 like", value, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1NotLike(String value) {
            addCriterion("pro_other1 not like", value, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1In(List<String> values) {
            addCriterion("pro_other1 in", values, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1NotIn(List<String> values) {
            addCriterion("pro_other1 not in", values, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1Between(String value1, String value2) {
            addCriterion("pro_other1 between", value1, value2, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther1NotBetween(String value1, String value2) {
            addCriterion("pro_other1 not between", value1, value2, "proOther1");
            return (Criteria) this;
        }

        public Criteria andProOther2IsNull() {
            addCriterion("pro_other2 is null");
            return (Criteria) this;
        }

        public Criteria andProOther2IsNotNull() {
            addCriterion("pro_other2 is not null");
            return (Criteria) this;
        }

        public Criteria andProOther2EqualTo(String value) {
            addCriterion("pro_other2 =", value, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2NotEqualTo(String value) {
            addCriterion("pro_other2 <>", value, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2GreaterThan(String value) {
            addCriterion("pro_other2 >", value, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2GreaterThanOrEqualTo(String value) {
            addCriterion("pro_other2 >=", value, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2LessThan(String value) {
            addCriterion("pro_other2 <", value, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2LessThanOrEqualTo(String value) {
            addCriterion("pro_other2 <=", value, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2Like(String value) {
            addCriterion("pro_other2 like", value, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2NotLike(String value) {
            addCriterion("pro_other2 not like", value, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2In(List<String> values) {
            addCriterion("pro_other2 in", values, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2NotIn(List<String> values) {
            addCriterion("pro_other2 not in", values, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2Between(String value1, String value2) {
            addCriterion("pro_other2 between", value1, value2, "proOther2");
            return (Criteria) this;
        }

        public Criteria andProOther2NotBetween(String value1, String value2) {
            addCriterion("pro_other2 not between", value1, value2, "proOther2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 23 21:11:30 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}