package com.aistar.pojo;

import java.io.Serializable;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_price
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Double proPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.writer_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer writerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer proStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_size
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String proSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_date
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String proDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.kind_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer kindId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.theme_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_material
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String proMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_kind
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private Integer proKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String proOther1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String proOther2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_describe
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private String proDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_id
     *
     * @return the value of product.pro_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_id
     *
     * @param proId the value for product.pro_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_name
     *
     * @return the value of product.pro_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_name
     *
     * @param proName the value for product.pro_name
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_price
     *
     * @return the value of product.pro_price
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Double getProPrice() {
        return proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_price
     *
     * @param proPrice the value for product.pro_price
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProPrice(Double proPrice) {
        this.proPrice = proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.writer_id
     *
     * @return the value of product.writer_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getWriterId() {
        return writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.writer_id
     *
     * @param writerId the value for product.writer_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setWriterId(Integer writerId) {
        this.writerId = writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_status
     *
     * @return the value of product.pro_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getProStatus() {
        return proStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_status
     *
     * @param proStatus the value for product.pro_status
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProStatus(Integer proStatus) {
        this.proStatus = proStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_size
     *
     * @return the value of product.pro_size
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getProSize() {
        return proSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_size
     *
     * @param proSize the value for product.pro_size
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProSize(String proSize) {
        this.proSize = proSize == null ? null : proSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_date
     *
     * @return the value of product.pro_date
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getProDate() {
        return proDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_date
     *
     * @param proDate the value for product.pro_date
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProDate(String proDate) {
        this.proDate = proDate == null ? null : proDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.kind_id
     *
     * @return the value of product.kind_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getKindId() {
        return kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.kind_id
     *
     * @param kindId the value for product.kind_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setKindId(Integer kindId) {
        this.kindId = kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.theme_id
     *
     * @return the value of product.theme_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.theme_id
     *
     * @param themeId the value for product.theme_id
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_material
     *
     * @return the value of product.pro_material
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getProMaterial() {
        return proMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_material
     *
     * @param proMaterial the value for product.pro_material
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProMaterial(String proMaterial) {
        this.proMaterial = proMaterial == null ? null : proMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_kind
     *
     * @return the value of product.pro_kind
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public Integer getProKind() {
        return proKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_kind
     *
     * @param proKind the value for product.pro_kind
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProKind(Integer proKind) {
        this.proKind = proKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_other1
     *
     * @return the value of product.pro_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getProOther1() {
        return proOther1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_other1
     *
     * @param proOther1 the value for product.pro_other1
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProOther1(String proOther1) {
        this.proOther1 = proOther1 == null ? null : proOther1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_other2
     *
     * @return the value of product.pro_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getProOther2() {
        return proOther2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_other2
     *
     * @param proOther2 the value for product.pro_other2
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProOther2(String proOther2) {
        this.proOther2 = proOther2 == null ? null : proOther2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_describe
     *
     * @return the value of product.pro_describe
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public String getProDescribe() {
        return proDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_describe
     *
     * @param proDescribe the value for product.pro_describe
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    public void setProDescribe(String proDescribe) {
        this.proDescribe = proDescribe == null ? null : proDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", proId=").append(proId);
        sb.append(", proName=").append(proName);
        sb.append(", proPrice=").append(proPrice);
        sb.append(", writerId=").append(writerId);
        sb.append(", proStatus=").append(proStatus);
        sb.append(", proSize=").append(proSize);
        sb.append(", proDate=").append(proDate);
        sb.append(", kindId=").append(kindId);
        sb.append(", themeId=").append(themeId);
        sb.append(", proMaterial=").append(proMaterial);
        sb.append(", proKind=").append(proKind);
        sb.append(", proOther1=").append(proOther1);
        sb.append(", proOther2=").append(proOther2);
        sb.append(", proDescribe=").append(proDescribe);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}