package com.aistar.mapper;

import com.aistar.pojo.CouponHave;
import com.aistar.pojo.CouponHaveExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CouponHaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int countByExample(CouponHaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int deleteByExample(CouponHaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int deleteByPrimaryKey(Integer haveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int insert(CouponHave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int insertSelective(CouponHave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    List<CouponHave> selectByExample(CouponHaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    CouponHave selectByPrimaryKey(Integer haveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") CouponHave record, @Param("example") CouponHaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int updateByExample(@Param("record") CouponHave record, @Param("example") CouponHaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int updateByPrimaryKeySelective(CouponHave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_have
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int updateByPrimaryKey(CouponHave record);
}