package com.aistar.mapper;

import com.aistar.pojo.Myorder;
import com.aistar.pojo.MyorderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MyorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int countByExample(MyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int deleteByExample(MyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int insert(Myorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int insertSelective(Myorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    List<Myorder> selectByExample(MyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    Myorder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") Myorder record, @Param("example") MyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int updateByExample(@Param("record") Myorder record, @Param("example") MyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int updateByPrimaryKeySelective(Myorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myorder
     *
     * @mbggenerated Mon Sep 23 21:11:30 CST 2019
     */
    int updateByPrimaryKey(Myorder record);
}